language: java
sudo: false # faster builds
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V

jdk:
  - oraclejdk8
  
script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
